### ISSUE TITLE
Question about evaluation

### ISSUE THREAD

**Issue by tagucci** [boudinfl/ake-datasets#1]
Hi, thanks for awesome repo!
I am a new to keyphrase extraction and would like to know whether I should evaluate my own model on `test.author.json`, `test.readers.json` or `test.combined.json` on NUS/SemEval2010/etc. On the other hand, there are `test.contr.json` and `test.uncontr.json` on Inspec. In your [MultipartiteRank](https://arxiv.org/abs/1803.08721) paper, you used NUS and SemEval2010. Which json file did you used to evaluate your model in the paper?

thanks.

**Comment by boudinfl** [comment]
Hi @tagucci,

In the MultipartiteRank paper, and as in most previous works, the `test.combined.json` (i.e. authors+readers) and the `test.uncontr.json` (uncontrolled vocabulary) are used for SemEval-2010/NUS and Inspec evaluation.

Best regards,
